ota:
  password: !secret wifi_password

wifi:
  use_address: $ipv4
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: $ipv4
    gateway: 0.0.0.0
    subnet: 255.255.255.0
  
esphome:
  name: $host
  board: esp8285
  platform: ESP8266
  build_path: build/${host}_minimal
  arduino_version: LATEST
