# github key: 4be3ce0720c7d7fedf6fd1505501723dcb94dd3d

default_config:

http:
  server_port: 443
  base_url: https://www.phong.live
  ssl_certificate: /ssl/phong_live.crt
  ssl_key: /ssl/phong_live.key
  cors_allowed_origins:
  - https://google.com
  - https://www.home-assistant.io
  - https://cast.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
  - 10.0.0.0/16
  - 192.168.0.0/16
  - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 10

homeassistant:
  name: Home
  latitude: 21.0197167
  longitude: 105.8228603
  elevation: 10
  unit_system: metric
  time_zone: Asia/Ho_Chi_Minh

  customize: !include customizes/customizes.yaml
  customize_glob: !include customizes/customize_globs.yaml
  customize_domain: !include customizes/customize_domains.yaml

frontend:
  themes: !include_dir_merge_named themes

script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes
group: !include_dir_merge_named groups
camera: !include_dir_merge_list cameras
automation: !include_dir_merge_list automations
media_player: !include_dir_merge_list media_players
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
lock: !include_dir_merge_list locks
alarm_control_panel: !include_dir_merge_list alarms
