# github key: 4be3ce0720c7d7fedf6fd1505501723dcb94dd3d

default_config:

homeassistant:
  name: Home
  # internal_url: "http://homeassistant.local:8123"
  # base_url: "https://www.phong.live"
  latitude: 21.0197167
  longitude: 105.8228603
  elevation: 98
  unit_system: metric
  time_zone: Asia/Ho_Chi_Minh

  customize: !include customizes/customizes.yaml
  customize_glob: !include customizes/customize_globs.yaml
  customize_domain: !include customizes/customize_domains.yaml

frontend:
  themes: !include_dir_merge_named themes

script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations

lock: !include_dir_merge_list locks
sensor: !include_dir_merge_list sensors
camera: !include_dir_merge_list cameras
media_player: !include_dir_merge_list media_players
binary_sensor: !include_dir_merge_list binary_sensors
alarm_control_panel: !include_dir_merge_list alarms
