- platform: template
  name: Front Door
  value_template: "{{ is_state('binary_sensor.wyzesense_778cabc6', 'off') }}"
  lock:
  - service: system_log.write
    data:
      message: send lock door command
  unlock:
  - service: system_log.write
    data:
      message: send unlock door command

