- platform: template
  name: Front Door
  value_template: "{{ is_state('binary_sensor.wyzesense_778305f1', 'on') }}"
  lock:
    - service: notify.notify
      data:
        title: Locked
        message: Your door is looked
  unlock:
    - service: notify.notify
      data:
        title: Unlocked
        message: Your door is unlooked

