#<<: !include templates/espcam.yaml

ota:
  password: !secret wifi_password

api:
  reboot_timeout: 0s

logger:
  baud_rate: 9600

web_server:

captive_portal:

wifi: !include templates/wifi.yaml

substitutions:
  host: espcam_3
  area: Camera 3
  ipv4: 10.0.0.23

esphome:
  name: $host
  platform: ESP32
  board: esp32cam
  build_path: build/$host
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 240000000L
    board_build.f_flash: 80000000L

status_led:
  pin: 33