<<: !include templates/switch3.yaml

substitutions:
  host: switch_bedroom
  area: Bedroom
  ipv4: 10.0.0.54

i2c:
  sda: 3
  scl: 1
  scan: yes

sensor:
- <<: !include sensors/dht12.yaml

remote_transmitter:
  id: transmitter
  pin:
    number: 0
    inverted: true
  carrier_duty_percent: 50%

climate:
- platform: daikin
  name: $area AC
  sensor: temperature
  transmitter_id: transmitter
  visual:
    min_temperature: 18 °C
    max_temperature: 30 °C

binary_sensor:
- platform: gpio
  id: input_1
  pin:
    number: GPIO14
    inverted: true
  on_press:
  - homeassistant.service:
      service: homeassistant.toggle
      data:
        entity_id: light.bedroom_light
#  - http_request.post:
#      url: http://10.0.0.10/light/bedroom_light/toggle

- platform: gpio
  id: input_2
  pin:
    number: GPIO05
    inverted: true
  on_press:
  - light.toggle: light_2
#  - http_request.post:
#      url: http://10.0.0.10/light/bedroom_light/toggle

- platform: gpio
  id: input_3
  pin:
    number: GPIO12
    inverted: true
  on_press:
  - homeassistant.service:
      service: homeassistant.toggle
      data:
        entity_id: light.balcony_light
#  - http_request.post:
#      url: http://10.0.0.11/light/balcony_light/toggle
