name: ${name}
platform: ESP8266
board: esp01_1m
build_path: build/${name}
esp8266_restore_from_flash: true
platformio_options:
  upload_speed: 921600
  board_build.f_cpu: 160000000L
  board_build.f_flash: 80000000L