adc_pin: "A0"
  
led_pin: "16"
uart1_tx_pin: "02"

boot_pin: "0"

uart0_tx_pin: "01"
uart0_rx_pin: "03"

input_pin_1: "14"
input_pin_2: "05"
input_pin_3: "12"

output_pin_1: "04"
output_pin_2: "15"
output_pin_3: "13"