adc_pin: "A0"
led_pin: "GPIO16"
boot_pin: "GPIO00"
input_pin_1: "GPIO05"
input_pin_2: "GPIO16"
input_pin_3: "GPIO03"
input_pin_4: "GPIO12"
output_pin_1: "GPIO15"
output_pin_2: "GPIO14"
output_pin_3: "GPIO04"
output_pin_4: "GPIO13"