- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: last_boot
    - type: processor_use
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m

    - type: ipv4_address
      arg: eth0
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0

#    - type: ipv4_address
#      arg: wlan0
#    - type: network_in
#      arg: wlan0
#    - type: network_out
#      arg: wlan0
#    - type: packets_in
#      arg: wlan0
#    - type: packets_out
#      arg: wlan0
#    - type: throughput_network_in
#      arg: wlan0
#    - type: throughput_network_out
#      arg: wlan0