- platform: template
  panels:
    safe_alarm_panel:
    value_template: "{{ states.alarm_control_panel.real_alarm }}"
    arm_away:
      service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.real_alarm
        code: !secret alarm_code
    arm_home:
      service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.real_alarm
        code: !secret alarm_code
    disarm:
      - condition: state
        entity_id: person.phong
        state: 'home'
      - service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.real_alarm
          code: !secret alarm_code