substitutions:
  name: balcony
  area: Balcony
  
logger:

<<: !include share/common.yaml

wifi:
#  use_address: 10.0.0.196
  <<: !include share/wifi.yaml

esphome: !include share/esp8285.yaml

sensor:
  
  - platform: dht
    pin: 2
    update_interval: 15s
    temperature:
      id: temperature
      name: $name Temperature
    humidity:
      id: humidity
      name: $name Humidity

binary_sensor:

  - platform: gpio
    pin: 3
    name: $name Motion
    device_class: motion
    filters:
      - invert:
      - delayed_on_off: 300ms

  - platform: homeassistant
    name: $name Door
    entity_id: binary_sensor.wyzesense_777eacaf
    device_class: door
    
  - platform: gpio
    pin:
      number: 0
      inverted: true
    name: $name Button
    internal: true
    on_press: {}

output:
  
  - platform: gpio
    id: output_1
    pin: 12

light:
  
  - platform: binary
    output: output_1
    id: light_1
    name: $name Light