substitutions:
  name: kitchen
  area: Kitchen

<<: !include share/common.yaml

wifi:
#  use_address: 10.0.0.173
  <<: !include share/wifi.yaml

esphome:
  <<: !include share/esp8285.yaml

status_led:
  pin:
    number: 13
    inverted: true

binary_sensor:
  
  - platform: homeassistant
    name: $name Motion
    entity_id: binary_sensor.wyzesense_779241f5
    device_class: motion
  
  - platform: gpio
    pin:
      number: 0 # button pin
      inverted: true
    name: $name Button
    internal: true
    on_press: {}

#power_supply:
#
#  - id: psu_1
#    enable_time: 20ms
#    keep_on_time: 5s
#    pin: 12 # relay pin

output:
  
#  - platform: esp8266_pwm
#    id: output_1
#    pin: 1 # tx pin
#    power_supply: psu_1
#
#  - platform: esp8266_pwm
#    id: output_2
#    pin: 3 # rx pin
#    power_supply: psu_1
  
  - platform: gpio
    id: psu_1
    pin: 12 # relay pin

light:
  
  - platform: binary
    id: light_1
    name: $name Light
    output: psu_1

#  - platform: cwww
#    id: light_1
#    name: $name Light
#    warm_white: output_1
#    cold_white: output_2
#    cold_white_color_temperature: 6000 K
#    warm_white_color_temperature: 3000 K


