substitutions:
  name: living_room
  area: Living Room

<<: !include share/common.yaml

wifi:
#  use_address: 10.0.0.109
  <<: !include share/wifi.yaml

esphome: !include share/esp8285.yaml

binary_sensor:
  
  - platform: homeassistant
    name: $name Motion
    entity_id: binary_sensor.wyzesense_7793fdd5
    device_class: motion
  
  - platform: gpio
    pin:
      number: 0
      inverted: true
    name: $name Button
    internal: true
    on_press: {}

output:
  
  - platform: esp8266_pwm
    id: output_1
    pin: 1
    power_supply: psu_1
    
  - platform: esp8266_pwm
    id: output_2
    pin: 3
    power_supply: psu_1

light:
  
  - platform: cwww
    id: light_1
    name: $name Light
    warm_white: output_1
    cold_white: output_2
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K

power_supply:
  
  - id: psu_1
    enable_time: 20ms
    keep_on_time: 5s
    pin: 12

