
#- alias: Turn living room light ON when occupied
#  trigger:
#  - platform: state
#    to: 'on'
#    entity_id:
#    - binary_sensor.living_room_motion
#  action:
#  - service: light.turn_on
#    entity_id: light.living_room_light
#
#- alias: Turn living_room light OFF when cleared
#  trigger:
#  - platform: state
#    entity_id: binary_sensor.living_room_motion
#    to: 'off'
#    for: 00:01:00
#  action:
#  - service: light.turn_off
#    entity_id: light.living_room_light
#    data:
#      transition: 60

- alias: Turn bedroom light ON when occupied
  trigger:
  - platform: state
    to: 'on'
    entity_id:
    - binary_sensor.bedroom_motion
    - binary_sensor.bedroom_door
  action:
  - service: light.turn_on
    entity_id: light.bedroom_light

- alias: Turn bedroom light OFF when cleared
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_motion
    to: 'off'
    for: 00:10:00
  action:
  - service: light.turn_off
    entity_id: light.bedroom_light
    data:
      transition: 60

- alias: Turn bathroom light ON when occupied
  trigger:
  - platform: state
    to: 'on'
    entity_id:
    - binary_sensor.bathroom_motion
    - binary_sensor.bathroom_door
  action:
  - service: light.turn_on
    entity_id: light.bathroom_light

- alias: Turn bathroom light OFF when cleared
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for: 00:01:00
  action:
  - service: light.turn_off
    entity_id: light.bathroom_light
    data:
      transition: 120

- alias: Turn kitchen light ON when occupied
  trigger:
  - platform: state
    to: 'on'
    entity_id:
    - binary_sensor.kitchen_motion
    - binary_sensor.wyzesense_778cabc6 # front_door
  action:
  - service: light.turn_on
    entity_id: light.kitchen_light

- alias: Turn kitchen light OFF when cleared
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for: 00:15:00
  action:
  - service: light.turn_off
    entity_id: light.kitchen_light
