
- alias: Startup routine
  trigger:
  - platform: event
    event_type: homeassistant_start
  action:
  - service: notify.notify
    data:
      message: Home Assistant starting up

- alias: Shutdown routine
  trigger:
  - platform: event
    event_type: homeassistant_stop
  action:
  - service: notify.notify
    data:
      message: Home Assistant shutting down

- alias: Morning routine
  trigger:
  - platform: sun
    event: sunrise
  action:
  - scene: scene.morning
  - service: frontend.set_theme
    data:
      name: Google Light Theme
  - service: notify.notify
    data:
      message: Morning scene activated

- alias: Evening routine
  trigger:
  - platform: sun
    event: sunset
  action:
  - scene: scene.evening
  - service: frontend.set_theme
    data:
      name: Google Dark Theme
  - service: notify.notify
    data:
      message: Evening scene activated

- alias: Night routine
  trigger:
  - platform: time
    at: '23:00:00'
  action:
  - scene: scene.night
  - service: notify.notify
    data:
      message: Night scene activated
