
# bathroom light -> switch 1a

- alias: Sync bathroom light switch state ON
  trigger:
  - entity_id: light.bathroom_light
    platform: state
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.switch_1a

- alias: Sync bathroom light switch state OFF
  trigger:
  - entity_id: light.bathroom_light
    platform: state
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.switch_1a

# bathroom fan -> switch 1b

- alias: Sync bathroom fan switch state ON
  trigger:
  - entity_id: fan.bathroom_fan
    platform: state
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.switch_1b

- alias: Sync bathroom fan switch state OFF
  trigger:
  - entity_id: fan.bathroom_fan
    platform: state
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.switch_1b

# dining_room light -> switch 3a

- alias: Sync dining_room light switch state ON
  trigger:
  - entity_id: light.dining_room_light
    platform: state
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.switch_3a

- alias: Sync dining_room light switch state OFF
  trigger:
  - entity_id: light.dining_room_light
    platform: state
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.switch_3a

# alter light -> switch 3b

- alias: Sync alter light switch state ON
  trigger:
  - entity_id: light.alter_light
    platform: state
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.switch_3b

- alias: Sync alter light switch state OFF
  trigger:
  - entity_id: light.alter_light
    platform: state
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.switch_3b

# kitchen light -> switch 3c

- alias: Sync kitchen light switch state ON
  trigger:
  - entity_id: light.kitchen_light
    platform: state
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.switch_3c

- alias: Sync kitchen light switch state OFF
  trigger:
  - entity_id: light.kitchen_light
    platform: state
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.switch_3c

# living_room light -> switch 2a, 2b, 2c

- alias: Sync living room light switch state ON
  trigger:
  - entity_id: light.living_room_light
    platform: state
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id:
    - switch.switch_2a
    - switch.switch_2b
    - switch.switch_2c

- alias: Sync living room light switch state OFF
  trigger:
  - entity_id: light.living_room_light
    platform: state
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - switch.switch_2a
    - switch.switch_2b
    - switch.switch_2c
