- alias: SYNC BEDROOM LIGHT SWITCH ON
  trigger:
    - entity_id:
        - light.bedroom_light
        - switch.switch_4A
      platform: state
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.switch_4A
    - service: light.turn_on
      data:
        entity_id: light.bedroom_light
- alias: SYNC BEDROOM LIGHT SWITCH OFF
  trigger:
    - entity_id:
        - light.bedroom_light
        - switch.switch_4A
      platform: state
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.switch_4A
    - service: light.turn_off
      data:
        entity_id: light.bedroom_light

- alias: SYNC BEDROOM CURTAIN SWITCH ON
  trigger:
    - entity_id:
        - cover.bedroom_curtain
      platform: state
      to: 'open'
      for: 00:00:01
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.switch_4C
- alias: SYNC BEDROOM CURTAIN SWITCH ON 2
  trigger:
    - entity_id:
        - switch.switch_4C
      platform: state
      to: 'on'
  action:
    - service: cover.open_cover
      data:
        entity_id: cover.bedroom_curtain
- alias: SYNC BEDROOM CURTAIN SWITCH OFF
  trigger:
    - entity_id:
        - cover.bedroom_curtain
      platform: state
      to: 'close'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.switch_4C
- alias: SYNC BEDROOM CURTAIN SWITCH OFF 2
  trigger:
    - entity_id:
        - switch.switch_4C
      platform: state
      to: 'off'
  action:
    - service: cover.close_cover
      data:
        entity_id: cover.bedroom_curtain

- alias: SYNC BALCONY LIGHT SWITCH ON
  trigger:
    - entity_id:
        - light.balcony_light
        - switch.switch_4B
      platform: state
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.switch_4B
    - service: light.turn_on
      data:
        entity_id: light.balcony_light
- alias: SYNC BALCONY LIGHT SWITCH OFF
  trigger:
    - entity_id:
        - light.balcony_light
        - switch.switch_4B
      platform: state
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.switch_4B
    - service: light.turn_off
      data:
        entity_id: light.balcony_light
        
- alias: SYNC KITCHEN LIGHT SWITCH ON
  trigger:
    - entity_id:
        - light.kitchen_light
        - switch.switch_3A
        - switch.switch_2A
      platform: state
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.switch_3A
          - switch.switch_2A
    - service: light.turn_on
      data:
        entity_id: light.kitchen_light
- alias: SYNC KITCHEN LIGHT SWITCH OFF
  trigger:
    - entity_id:
        - light.kitchen_light
        - switch.switch_3A
        - switch.switch_2A
      platform: state
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.switch_3A
          - switch.switch_2A
    - service: light.turn_off
      data:
        entity_id: light.kitchen_light
        
- alias: SYNC DINING LIGHT SWITCH ON
  trigger:
    - entity_id:
        - light.dining_room_light
        - switch.switch_3B
        - switch.switch_2B
      platform: state
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.switch_3B
          - switch.switch_2B
    - service: light.turn_on
      data:
        entity_id: light.dining_room_light
- alias: SYNC DINING LIGHT SWITCH OFF
  trigger:
    - entity_id:
        - light.dining_room_light
        - switch.switch_3B
        - switch.switch_2B
      platform: state
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.switch_3B
          - switch.switch_2B
    - service: light.turn_off
      data:
        entity_id: light.dining_room_light
        
- alias: SYNC LIVING ROOM LIGHT SWITCH ON
  trigger:
    - entity_id:
        - light.living_room_light
        - switch.switch_3C
        - switch.switch_2C
      platform: state
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.switch_3C
          - switch.switch_2C
    - service: light.turn_on
      data:
        entity_id: light.living_room_light
- alias: SYNC LIVING ROOM LIGHT SWITCH OFF
  trigger:
    - entity_id:
        - light.living_room_light
        - switch.switch_3C
        - switch.switch_2C
      platform: state
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.switch_3C
          - switch.switch_2C
    - service: light.turn_off
      data:
        entity_id: light.living_room_light

- alias: SYNC BATHROOM LIGHT SWITCH ON
  trigger:
    - entity_id:
        - light.bathroom_light
        - switch.bathroom_light
      platform: state
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.bathroom_light
    - service: light.turn_on
      data:
        entity_id: light.bathroom_light
- alias: SYNC BATHROOM LIGHT SWITCH OFF
  trigger:
    - entity_id:
        - light.bathroom_light
        - switch.bathroom_light
      platform: state
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_light
    - service: light.turn_off
      data:
        entity_id: light.bathroom_light

- alias: SYNC BATHROOM FAN SWITCH ON
  trigger:
    - entity_id:
        - fan.bathroom_fan
        - switch.bathroom_fan
      platform: state
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.bathroom_fan
    - service: fan.turn_on
      data:
        entity_id: fan.bathroom_fan
- alias: SYNC BATHROOM FAN SWITCH OFF
  trigger:
    - entity_id:
        - fan.bathroom_fan
        - switch.bathroom_fan
      platform: state
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_fan
    - service: fan.turn_off
      data:
        entity_id: fan.bathroom_fan
