esphome:
  name: $name
  board: modwifi
  platform: ESP8266
  build_path: build/$name
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600
  includes:
    - components/dimmer.h
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  ap:
    ssid: $name
    password: !secret wifi_password
    ap_timeout: 0s

ota:
  password: !secret wifi_password

api:
  reboot_timeout: 0s

logger:
  baud_rate: 0

web_server:

remote_transmitter:
  pin: 1
  carrier_duty_percent: 100%

status_led:
  pin:
    number: 16
    inverted: true

globals:
  - id: last_value
    type: float
    initial_value: '5'
    restore_value: yes

sensor:
  - platform: custom
    lambda: >-
      int pins[] = { ${button_pin_3}, ${button_pin_2}, ${button_pin_1} };
      auto dimmer = new TouchDimmer(3, pins);
      App.register_component(dimmer);
      return { dimmer->value };
    sensors:
      - name: ${area}


binary_sensor:
  - platform: gpio
    id: input_1
    pin:
      number: ${button_pin_1}
      inverted: true
    on_press:
      - light.turn_on:
          id: light_1
          brightness: 100%
          transition_length: 0s
    on_release:
      - light.turn_off:
          id: light_1
          transition_length: 0s
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            code: '${code}0000101000000001'
            protocol: 2
            repeat:
              times: 3
              wait_time: 200ms
              
  - platform: gpio
    id: input_2
    pin:
      number: ${button_pin_2}
      inverted: true
    on_press:
      - light.turn_on:
          id: light_2
          brightness: 100%
          transition_length: 0s
    on_release:
      - light.turn_off:
          id: light_2
          transition_length: 500ms
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            code: '${code}0000101100000001'
            protocol: 2
            repeat:
              times: 3
              wait_time: 200ms
    
  - platform: gpio
    id: input_3
    pin:
      number: ${button_pin_3}
      inverted: true
    on_press:
      - light.turn_on:
          id: light_3
          brightness: 100%
          transition_length: 0s
    on_release:
      - light.turn_off:
          id: light_3
          transition_length: 500ms
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            code: '${code}0000110000000001'
            protocol: 2
            repeat:
              times: 3
              wait_time: 200ms


output:
  - platform: esp8266_pwm
    id: output_1
    pin: ${output_pin_1}
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: output_2
    pin: ${output_pin_2}
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: output_3
    pin: ${output_pin_3}
    frequency: 1000 Hz

light:
  - platform: monochromatic
    id: light_1
    output: output_1
  - platform: monochromatic
    id: light_2
    output: output_2
  - platform: monochromatic
    id: light_3
    output: output_3
