<<: !include .sonoff.yaml

binary_sensor:
  - platform: remote_receiver
    id: rf_1
    rc_switch_raw:
      code: '000001000000101100000001'
      protocol: 2
    on_press:
      then:
        - light.toggle: light_1

  - platform: gpio
    pin:
      number: 0
      inverted: true
    name: ${area} Button
    on_press:
      - light.toggle: light_1

  - platform: gpio
    pin:
      number: 2
      inverted: true
    name: ${area} RC

output:
  - platform: gpio
    pin: 12
    id: output_1

light:
  - platform: binary
    output: output_1
    id: light_1
    name: ${area} Light