<<: !include .common.yaml

wifi:
  <<: !include .wifi.yaml
  
esphome:
  name: $host
  board: esp8285
  platform: ESP8266
  build_path: build/$host
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 160000000L

status_led:
  pin:
    number: 13
    inverted: true
