<<: !include .sonoff.yaml

binary_sensor:
  - platform: remote_receiver
    id: rc_turn_on
    internal: true
    rc_switch_raw:
      code: '${code}0000101000000001' # 0x040A01
      protocol: 2
    on_press:
      - light.turn_on: light_1
  - platform: remote_receiver
    id: rc_toggle
    internal: true
    rc_switch_raw:
      code: '${code}0000101000000010' # 0x040A02
      protocol: 2
    on_press:
      - light.toggle: light_1
  - platform: remote_receiver
    id: rc_turn_off
    internal: true
    rc_switch_raw:
      code: '${code}0000101000000011' # 0x040A03
      protocol: 2
    on_press:
      - light.turn_off: light_1

  - platform: gpio
    pin:
      number: 0
      inverted: true
    name: ${area} Button
    internal: true
    on_press:
      - light.toggle: light_1

power_supply:
  - id: psu_1
    enable_time: 20ms
    keep_on_time: 5s
    pin: 12 # relay pin

output:
  - platform: esp8266_pwm
    id: output_1
    pin: 1 # tx pin
    power_supply: psu_1
    frequency: 100hz
  
  - platform: esp8266_pwm
    id: output_2
    pin: 3 # rx pin
    power_supply: psu_1
    frequency: 100hz

light:
  - platform: cwww
    id: light_1
    name: ${area} Light
    cold_white: output_1
    warm_white: output_2
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K