esphome:
  name: $name
  board: esp8285
  platform: ESP8266
  build_path: build/$name
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 0s
  ap:
    ssid: $name
    password: !secret wifi_password
#    ap_timeout: 0s

ota:
  password: !secret wifi_password

api:
#  reboot_timeout: 0s

logger:
  baud_rate: 0

web_server:

status_led:
  pin:
    number: 13
    inverted: true
