<<: !include .common.yaml

esphome:
  name: $host
  board: modwifi
  platform: ESP8266
  build_path: build/$host
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 160000000L

http_request:
  useragent: esphome/$host
  timeout: 1s

status_led:
  pin:
    number: 16
    inverted: true

api:
  reboot_timeout: 0s
  services:
  - service: sync_button_state
    variables:
      button: int
      state: bool
    then:
    - lambda: >-
        if (state) {
          switch (button) {
            case 1: id(output_1).turn_on(); break;
            case 2: id(output_2).turn_on(); break;
            case 3: id(output_3).turn_on(); break;
          }
        } else {
         switch (button) {
           case 1: id(output_1).turn_off(); break;
           case 2: id(output_2).turn_off(); break;
           case 3: id(output_3).turn_off(); break;
         }
        }


switch:
- platform: gpio
  id: output_1
  pin: $output_pin_1
- platform: gpio
  id: output_2
  pin: $output_pin_2
- platform: gpio
  id: output_3
  pin: $output_pin_3

script:
- id: toggle_switch_1
  then:
  - if:
      condition:
        switch.is_on: output_1
      then:
      - http_request.post:
          url: http://${link_1}/turn_on
      else:
      - http_request.post:
          url: http://${link_1}/turn_off
- id: toggle_switch_2
  then:
  - if:
      condition:
        switch.is_on: output_2
      then:
      - http_request.post:
          url: http://${link_2}/turn_on
      else:
      - http_request.post:
          url: http://${link_2}/turn_off
- id: toggle_switch_3
  then:
  - if:
      condition:
        switch.is_on: output_3
      then:
      - http_request.post:
          url: http://${link_3}/turn_on
      else:
      - http_request.post:
          url: http://${link_3}/turn_off

binary_sensor:
- platform: gpio
  id: input_1
  pin:
    number: $input_pin_1
    inverted: true
  on_press:
  - then:
    - switch.toggle: output_1
    - script.execute: toggle_switch_1
- platform: gpio
  id: input_2
  pin:
    number: $input_pin_2
    inverted: true
  on_press:
  - then:
    - switch.toggle: output_2
    - script.execute: toggle_switch_2
- platform: gpio
  id: input_3
  pin:
    number: $input_pin_3
    inverted: true
  on_press:
  - then:
    - switch.toggle: output_3
    - script.execute: toggle_switch_3

