<<: !include .common.yaml

esphome:
  name: $host
  board: modwifi
  platform: ESP8266
  build_path: build/$host
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 160000000L

http_request:
  useragent: esphome/$host
  timeout: 1s

status_led:
  pin:
    number: 16
    inverted: true

api:
  reboot_timeout: 0s
  services:
  - service: sync_button_state
    variables:
      button: int
      state: bool
    then:
    - lambda: >-
        if (state) {
          switch (button) {
            case 1: id(output_1).turn_on(); break;
            case 2: id(output_2).turn_on(); break;
            case 3: id(output_3).turn_on(); break;
          }
        } else {
         switch (button) {
           case 1: id(output_1).turn_off(); break;
           case 2: id(output_2).turn_off(); break;
           case 3: id(output_3).turn_off(); break;
         }
        }

switch:
- platform: gpio
  id: output_1
  pin: GPIO04
  
- platform: gpio
  id: output_2
  pin: GPIO15
  
- platform: gpio
  id: output_3
  pin: GPIO13

globals:
  - id: var1
    type: String
  - id: var2
    type: String

script:
- id: sync_state
  then:
  - if:
      condition:
        lambda: 'id(id(var1));'
      then:
        - http_request.post: 'http://{{ var2 }}/turn_on'
      else:
        - http_request.post: 'http://{{ var2 }}/turn_off'
    
binary_sensor:
- platform: gpio
  id: input_1
  pin:
    number: GPIO14
    inverted: true
  on_press:
  - then:
    - lambda: >-
        id(var1) = "output_1";
        id(var2) = "$link_1";
    - switch.toggle: output_1
    - script.execute: sync_state
- platform: gpio
  id: input_2
  pin:
    number: GPIO05
    inverted: true
  on_press:
  - then:
    - lambda: >-
        id(var1) = "output_2";
        id(var2) = "$link_2";
    - switch.toggle: output_2
    - script.execute: sync_state
- platform: gpio
  id: input_3
  pin:
    number: GPIO12
    inverted: true
  on_press:
  - then:
    - lambda: >-
        id(var1) = "output_3";
        id(var2) = "$link_3";
    - switch.toggle: output_3
    - script.execute: sync_state

