esphome:
  name: switch_$id
  board: modwifi
  platform: ESP8266
  build_path: build/switch_$id
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  use_address: $address
  manual_ip:
    static_ip: 10.0.0.$id
    gateway: 10.0.0.1
    subnet: 255.0.0.0
  ap:
    ssid: switch_$id wifi
    password: !secret wifi_password
    ap_timeout: 0s

ota:
  password: !secret wifi_password

api:
  reboot_timeout: 0s

logger:
  baud_rate: 0

web_server:

http_request:
  useragent: esphome/switch_$id
  timeout: 1s

binary_sensor:
  
  - platform: gpio
    id: button_1
    pin:
      number: 14
      inverted: true
    on_release:
      - switch.turn_off: switch_1
    on_press:
      then:
        - switch.turn_on: switch_1
        - if:
            condition:
              api.connected:
            then:
              - homeassistant.service:
                  service: homeassistant.toggle
                  data:
                    entity_id: ${button_1_domain}.${button_1_entity_id}
            else:
              - http_request.post:
                  url: http://${button_1_host}/${button_1_domain}/${button_1_entity_id}/toggle
  
  - platform: gpio
    id: button_2
    pin:
      number: 5
      inverted: true
    on_release:
      - switch.turn_off: switch_2
    on_press:
      then:
        - switch.turn_on: switch_2
        - if:
            condition:
              api.connected:
            then:
              - homeassistant.service:
                  service: homeassistant.toggle
                  data:
                    entity_id: ${button_2_domain}.${button_2_entity_id}
            else:
              - http_request.post:
                  url: http://${button_2_host}/${button_2_domain}/${button_2_entity_id}/toggle
  
  - platform: gpio
    id: button_3
    pin:
      number: 12
      inverted: true
    on_release:
      - switch.turn_off: switch_3
    on_press:
      then:
        - switch.turn_on: switch_3
        - if:
            condition:
              api.connected:
            then:
              - homeassistant.service:
                  service: homeassistant.toggle
                  data:
                    entity_id: ${button_3_domain}.${button_3_entity_id}
            else:
              - http_request.post:
                  url: http://${button_3_host}/${button_3_domain}/${button_3_entity_id}/toggle


switch:
  
  - platform: gpio
    id: switch_1
    pin: 4
  
  - platform: gpio
    id: switch_2
    pin: 15
  
  - platform: gpio
    id: switch_3
    pin: 13
  