<<: !include .common.yaml

esphome:
  name: $host
  board: modwifi
  platform: ESP8266
  build_path: build/$host
  esp8266_restore_from_flash: true

http_request:
  useragent: esphome/$name

status_led:
  pin:
    number: 16
    inverted: true

script:
- id: toggle_switch_1
  then:
  - if:
      condition:
        switch.is_on: switch_1
      then:
      - http_request.post:
          url: http://${link_1}/turn_on
      else:
      - http_request.post:
          url: http://${link_1}/turn_off
- id: toggle_switch_2
  then:
  - if:
      condition:
        switch.is_on: switch_2
      then:
      - http_request.post:
          url: http://${link_2}/turn_on
      else:
      - http_request.post:
          url: http://${link_2}/turn_off
- id: toggle_switch_3
  then:
  - if:
      condition:
        switch.is_on: switch_3
      then:
      - http_request.post:
          url: http://${link_3}/turn_on
      else:
      - http_request.post:
          url: http://${link_3}/turn_off

switch:
- platform: gpio
  id: switch_1
  pin: $output_pin_1
  name: ${name}A
- platform: gpio
  id: switch_2
  pin: $output_pin_2
  name: ${name}B
- platform: gpio
  id: switch_3
  pin: $output_pin_3
  name: ${name}C

binary_sensor:
- platform: gpio
  id: input_1
  pin:
    number: $input_pin_1
    inverted: true
  on_press:
  - then:
    - switch.toggle: switch_1
    - script.execute: toggle_switch_1
- platform: gpio
  id: input_2
  pin:
    number: $input_pin_2
    inverted: true
  on_press:
  - then:
    - switch.toggle: switch_2
    - script.execute: toggle_switch_2
- platform: gpio
  id: input_3
  pin:
    number: $input_pin_3
    inverted: true
  on_press:
  - then:
    - switch.toggle: switch_3
    - script.execute: toggle_switch_3
