esphome:
  name: $name
  board: modwifi
  platform: ESP8266
  build_path: build/$name
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  ap:
    ssid: $name
    password: !secret wifi_password
    ap_timeout: 0s

ota:
  password: !secret wifi_password

api:
  reboot_timeout: 0s

logger:
  baud_rate: 0

web_server:

status_led:
  pin:
    number: 16
    inverted: true

output:
  
  - platform: esp8266_pwm
    id: output_1
    frequency: 100hz
    pin: 4
  
  - platform: esp8266_pwm
    id: output_2
    frequency: 100hz
    pin: 15
  
  - platform: esp8266_pwm
    id: output_3
    frequency: 100hz
    pin: 13
    
light:
  
  - platform: monochromatic
    id: light_1
    output: output_1

  - platform: monochromatic
    id: light_2
    output: output_2

  - platform: monochromatic
    id: light_3
    output: output_3
    
binary_sensor:
  
  - platform: gpio
    id: input_1
    pin:
      number: 14
      inverted: true
    on_release:
      - light.turn_off: light_1
    on_press:
      then:
        - light.turn_on:
            id: light_1
            transition_length: 0s

  - platform: gpio
    id: input_2
    pin:
      number: 5
      inverted: true
    on_release:
      - light.turn_off: light_2
    on_press:
      then:
        - light.turn_on:
            id: light_2
            transition_length: 0s

  - platform: gpio
    id: input_3
    pin:
      number: 12
      inverted: true
    on_release:
      - light.turn_off: light_3
    on_press:
      then:
        - light.turn_on:
            id: light_3
            transition_length: 0s
