esphome:
  name: $name
  board: modwifi
  platform: ESP8266
  build_path: build/$name
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  ap:
    ssid: $name
    password: !secret wifi_password
    ap_timeout: 0s

ota:
  password: !secret wifi_password

api:
  reboot_timeout: 0s

logger:
  baud_rate: 0

web_server:

status_led:
  pin:
    number: 16
    inverted: true

#remote_transmitter:
#  pin: 3
#  carrier_duty_percent: 100%

switch:
  
  - platform: gpio
    id: switch_1
    pin: 4
  
  - platform: gpio
    id: switch_2
    pin: 15
  
  - platform: gpio
    id: switch_3
    pin: 13

  - platform: gpio
    pin:
      number: 0
      inverted: true
    name: ${area} Output

binary_sensor:
  
  - platform: gpio
    id: input_1
    pin:
      number: 14
      inverted: true
    on_release:
      - switch.turn_off: switch_1
    on_press:
      then:
        - switch.turn_on: switch_1
#        - remote_transmitter.transmit_rc_switch_raw:
#            code: '100010000000000010111110'
#            protocol: 2

  - platform: gpio
    id: input_2
    pin:
      number: 5
      inverted: true
    on_release:
      - switch.turn_off: switch_2
    on_press:
      then:
        - switch.turn_on: switch_2
#        - remote_transmitter.transmit_rc_switch_raw:
#            code: '100010000000000010111110'
#            protocol: 2

  - platform: gpio
    id: input_3
    pin:
      number: 12
      inverted: true
    on_release:
      - switch.turn_off: switch_3
    on_press:
      then:
        - switch.turn_on: switch_3
#        - remote_transmitter.transmit_rc_switch_raw:
#            code: '100010000000000010111110'
#            protocol: 2
