use_address: ${host}.local
networks:
- ssid: !secret wifi_ssid
  password: !secret wifi_password
manual_ip:
  static_ip: $ipv4
  gateway: 10.0.0.1
  subnet: 255.255.255.0
  dns1: 1.1.1.1
  dns2: 1.0.0.1
ap:
  ssid: ${name}
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.0.0.1
    gateway: 10.0.0.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 1.0.0.1