substitutions:
  host: balcony
  name: Balcony
  ipv4: 10.0.0.11

<<: !include .sonoff_light.yaml

sensor:
- platform: dht
  pin: 2
  update_interval: 10s
  temperature:
    id: temperature
    name: $name Temperature
  humidity:
    id: humidity
    name: $name Humidity

binary_sensor:
