<<: !include templates/sonoff_light.yaml

substitutions:
  host: light_balcony
  area: Balcony
  ipv4: 10.0.0.11

sensor:
#- <<: !include sensors/rssi.yaml
#- <<: !include sensors/uptime.yaml
- <<: !include sensors/dht11.yaml
