<<: !include templates/sonoff_light.yaml

substitutions:
  host: light_balcony
  area: Balcony
  ipv4: 10.0.0.11

# sensor:
# - platform: dht
#   pin: 2
#   model: DHT22
#   temperature:
#     id: temperature
#     name: $area Temperature
#     on_value:
#     - lambda: ESPNow.send("pub temperature_balcony " + String(id(temperature).state));
#   humidity:
#     id: humidity
#     name: $area Humidity
#     on_value:
#     - lambda: ESPNow.send("pub humidity_balcony " + String(id(temperature).state));
