substitutions:
  host: bathroom
  name: Bathroom
  ipv4: 10.0.0.12

<<: !include .sonoff_light_cw.yaml

binary_sensor:

power_supply: []

output:
- platform: esp8266_pwm
  id: output_1
  pin: 1 # tx pin
  frequency: 100hz

- platform: esp8266_pwm
  id: output_2
  pin: 3 # rx pin
  frequency: 100hz

- platform: gpio
  id: output_3
  pin: 12

fan:
  - platform: binary
    output: output_3
    id: fan_1
    name: $name Fan