<<: !include templates/sonoff.yaml

substitutions:
  host: light_bathroom
  area: Bathroom
  ipv4: 10.0.0.12

output:

- platform: esp8266_pwm
  id: output_1
  pin: 1 # tx pin
  frequency: 100hz

- platform: esp8266_pwm
  id: output_2
  pin: 3 # rx pin
  frequency: 100hz

- platform: gpio
  id: output_3
  pin: 12


fan:

- platform: binary
  output: output_3
  id: fan_1
  name: $area Fan

light:

- platform: cwww
  id: light_1
  name: $area Light
  cold_white: output_1
  warm_white: output_2
  cold_white_color_temperature: 6000 K
  warm_white_color_temperature: 3000 K

switch:

- platform: template
  id: switch_1
  lambda: return digitalRead(12);
  on_turn_on:
  - lambda: ESPNow.send("pub fan_bathroom on");
  on_turn_off:
  - lambda: ESPNow.send("pub fan_bathroom off");

- platform: template
  id: switch_2
  lambda: |-
    return digitalRead(1) || digitalRead(3);
  on_turn_on:
  - lambda: ESPNow.send("pub light_bathroom on");
  on_turn_off:
  - lambda: ESPNow.send("pub light_bathroom off");

custom_component:
  lambda: |-
    ESPNow.begin();
    ESPNow.on("set light_bathroom toggle", []() {
      id(light_1)->toggle().perform();
    });
    ESPNow.on("set fan_bathroom toggle", []() {
      id(switch_1)->toggle();
    });
    return {};
