substitutions:
  host: living_room
  name: Living Room
  ipv4: 10.0.0.16

<<: !include .sonoff_light_cw.yaml

binary_sensor:
- platform: homeassistant
  name: $name Motion
  entity_id: binary_sensor.wyzesense_7793fdd5
  device_class: motion
