<<: !include templates/sonoff.yaml

substitutions:
  host: sonoff_1
  area: None
  ipv4: 10.0.0.17

status_led:
  pin: 2

light:
  platform: binary
  output: output_1
  id: light_1
  name: Light

output:
  platform: gpio
  id: output_1
  pin: 13

switch:
  platform: gpio
  pin:
    number: 12
    inverted: true
  id: switch_1
  name: Relay
  on_turn_on:
  - light.turn_on: light_1
  on_turn_off:
  - light.turn_off: light_1

binary_sensor:
  platform: gpio
  pin:
    number: 0
    inverted: true
  id: button_1
  name: Button
  on_press:
  - switch.toggle: switch_1
