<<: !include templates/common.yaml

substitutions:
  host: espcam_3
  area: Camera 3
  ipv4: 10.0.0.23

esphome:
  name: $host
  platform: ESP32
  board: esp32cam
  build_path: build/$host
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 240000000L
    board_build.f_flash: 80000000L

spi:
  miso_pin: 12
  mosi_pin: 13
  clk_pin: 14

pn532:
  cs_pin: 15
  update_interval: 1s

binary_sensor:
- platform: pn532
  uid: 2A-56-8E-16
  name: "PN532 NFC Tag"