<<: !include .switch.yaml

substitutions:
  <<: !include .pinout_tuya_switch.yaml
  host: switch_1
  name: Switch 1
  ipv4: 10.0.0.51

  link_1: 10.0.0.12/light/bathroom_light
  link_2: 10.0.0.12/fan/bathroom_fan
  link_3: 10.0.0.12/switch/water_heater