<<: !include templates/switch.yaml

substitutions:
  host: switch_bathroom
  area: Bathroom
  ipv4: 10.0.0.51

output:
light:
switch:
- platform: gpio
  id: switch_1
  pin: 4
  
- platform: gpio
  id: switch_2
  pin: 15

- platform: gpio
  id: switch_3
  pin: 13
  name: $area Water Heater
  on_turn_on:
  - lambda: ESPNow.send("pub boiler_bathroom on");
  on_turn_off:
  - lambda: ESPNow.send("pub boiler_bathroom off");

http_request:

binary_sensor:

- platform: gpio
  id: touch_1
  pin:
    number: 14
    mode: INPUT_PULLUP
    inverted: true
  on_press:
    if:
      condition: wifi.connected
      then:
      - http_request.post: http://10.0.0.12/light/bathroom_light/toggle
      else:
      - lambda: ESPNow.send("set light_bathroom toggle");

- platform: gpio
  id: touch_2
  pin:
    number: 5
    mode: INPUT_PULLUP
    inverted: true
  on_press:
    if:
      condition: wifi.connected
      then:
      - http_request.post: http://10.0.0.12/fan/bathroom_fan/toggle
      else:
      - lambda: ESPNow.send("set fan_bathroom toggle");

- platform: gpio
  id: touch_3
  pin:
    number: 12
    mode: INPUT_PULLUP
    inverted: true
  on_press:
  - switch.toggle: switch_3
  
custom_component:
  lambda: |-
    ESPNow.begin();
    ESPNow.on("pub light_bathroom on", []() {
      id(switch_1)->turn_on();
    });
    ESPNow.on("pub light_bathroom off", []() {
      id(switch_1)->turn_off();
    });
    ESPNow.on("pub fan_bathroom on", []() {
      id(switch_2)->turn_on();
    });
    ESPNow.on("pub fan_bathroom off", []() {
      id(switch_2)->turn_off();
    });
    
    ESPNow.on("set boiler_bathroom on", []() {
      id(switch_3)->turn_on();
    });
    ESPNow.on("set boiler_bathroom off", []() {
      id(switch_3)->turn_off();
    });
    ESPNow.on("set boiler_bathroom toggle", []() {
      id(switch_3)->toggle();
    });
    ESPNow.on("req boiler_bathroom", []() {
      if (digitalRead(13)) {
        ESPNow.send("pub boiler_bathroom on");
      } else {
        ESPNow.send("pub boiler_bathroom off");
      }
    });

    ESPNow.send("req bathroom");
    return {};
  