<<: !include templates/switch.yaml

substitutions:
  host: switch_bathroom
  area: Bathroom
  ipv4: 10.0.0.51

output:
light:
switch:
- platform: gpio
  id: switch_1
  pin: 4
  
- platform: gpio
  id: switch_2
  pin: 15

- platform: gpio
  id: switch_3
  pin: 13
  name: $area Water Heater
  on_turn_on:
  - lambda: ESPNow.send("pub boiler_bathroom on");
  on_turn_off:
  - lambda: ESPNow.send("pub boiler_bathroom off");

binary_sensor:

- platform: gpio
  id: touch_1
  pin:
    number: 14
    mode: INPUT_PULLUP
    inverted: true
  on_press:
  - lambda: ESPNow.send("set bathroom_light toggle");

- platform: gpio
  id: touch_2
  pin:
    number: 5
    mode: INPUT_PULLUP
    inverted: true
  on_press:
  - lambda: ESPNow.send("set bathroom_fan toggle");

- platform: gpio
  id: touch_3
  pin:
    number: 12
    mode: INPUT_PULLUP
    inverted: true
  on_press:
  - switch.toggle: switch_1
  
custom_component:
  lambda: |-
    ESPNow.begin();
    ESPNow.on("pub bathroom_light on", []() {
      id(switch_1)->turn_on();
    });
    ESPNow.on("pub bathroom_light off", []() {
      id(switch_1)->turn_off();
    });
    ESPNow.on("pub bathroom_fan on", []() {
      id(switch_2)->turn_on();
    });
    ESPNow.on("pub bathroom_fan off", []() {
      id(switch_2)->turn_off();
    });
    
    ESPNow.on("set boiler_bathroom on", []() {
      id(switch_3)->turn_on();
    });
    ESPNow.on("set boiler_bathroom off", []() {
      id(switch_3)->turn_off();
    });
    ESPNow.on("set boiler_bathroom toggle", []() {
      id(switch_3)->toggle();
    });
    ESPNow.on("req boiler_bathroom", []() {
      if (digitalRead(13)) {
        ESPNow.send("pub boiler_bathroom on");
      } else {
        ESPNow.send("pub boiler_bathroom off");
      }
    });

    ESPNow.send("req light_bathroom");
    ESPNow.send("req fan_bathroom");
    return {};
  