<<: !include templates/switch.yaml

substitutions:
  host: switch_living_room
  area: Living Room
  ipv4: 10.0.0.52

  link_1: 10.0.0.16
  link_2: 10.0.0.16/light/living_room_light
  link_3: 10.0.0.16
