<<: !include templates/switch.yaml

substitutions:
  host: switch_living_room
  area: Living Room
  ipv4: 10.0.0.52

  target_1: light_living_room
  target_2: light_living_room
  target_3: light_living_room
  