<<: !include templates/switch.yaml

substitutions:
  host: switch_living_room
  area: Living Room
  ipv4: 10.0.0.52

output:

- platform: esp8266_pwm
  id: output_1
  pin: GPIO04

- platform: esp8266_pwm
  id: output_2
  pin: GPIO15

- platform: esp8266_pwm
  id: output_3
  pin: GPIO13

light:

- platform: monochromatic
  id: light_1
  output: output_1
  default_transition_length: 50ms

- platform: monochromatic
  id: light_2
  output: output_2
  default_transition_length: 50ms

- platform: monochromatic
  id: light_3
  output: output_3
  default_transition_length: 50ms

binary_sensor:

- platform: gpio
  id: input_1
  pin:
    number: GPIO14
    mode: INPUT_PULLUP
    inverted: true
  on_press:
  - lambda: ESPNow.send("set living_room_light toggle");

- platform: gpio
  id: input_2
  pin:
    number: GPIO05
    mode: INPUT_PULLUP
    inverted: true
  on_press:
  - lambda: ESPNow.send("set living_room_light toggle");

- platform: gpio
  id: input_3
  pin:
    number: GPIO12
    mode: INPUT_PULLUP
    inverted: true
  on_press:
  - lambda: ESPNow.send("set living_room_light toggle");

custom_component:
  lambda: |-
    ESPNow.init();
    
    ESPNow.on("pub living_room_light on", []() {
      id(light_1)->turn_on().perform();
      id(light_2)->turn_on().perform();
      id(light_3)->turn_on().perform();
    });
    ESPNow.on("pub living_room_light off", []() {
      id(light_1)->turn_off().perform();
      id(light_2)->turn_off().perform();
      id(light_3)->turn_off().perform();
    });
    
    return {};
  