<<: !include templates/switch.yaml

substitutions:
  host: switch_living_room
  area: Living Room
  ipv4: 10.0.0.52

  target_1: light_living_room
  target_2: light_living_room
  target_3: light_living_room


custom_component:
  lambda: |-
    ESPNow.begin();
    
    ESPNow.on("pub $target_1 on", []() {
      id(light_1)->turn_off().perform();
    });
    ESPNow.on("pub $target_1 off", []() {
      id(light_1)->turn_on().perform();
    });

    ESPNow.on("pub $target_2 on", []() {
      id(light_2)->turn_off().perform();
    });
    ESPNow.on("pub $target_2 off", []() {
      id(light_2)->turn_on().perform();
    });

    ESPNow.on("pub $target_3 on", []() {
      id(light_3)->turn_off().perform();
    });
    ESPNow.on("pub $target_3 off", []() {
      id(light_3)->turn_on().perform();
    });

    ESPNow.send("req $target_1");
    ESPNow.send("req $target_2");
    ESPNow.send("req $target_3");

    return {};
  
  