<<: !include .switch.yaml

substitutions:
  host: switch_2
  name: Living Room
  ipv4: 10.0.0.52

  link_1: 10.0.0.16
  link_2: 10.0.0.16/light/living_room_light
  link_3: 10.0.0.16

i2c:
  sda: 3
  scl: 1
  scan: yes

sensor:
- platform: dht12
  temperature:
    name: $name Temperature
  humidity:
    name: $name Humidity
  update_interval: 15s