<<: !include .switch.yaml

substitutions:
  host: switch_3
  name: Dining Room
  ipv4: 10.0.0.53

  link_1: 10.0.0.13/light/dining_room_light
  link_2: 10.0.0.14/light/alter_light
  link_3: 10.0.0.15/light/kitchen_light
