<<: !include templates/switch.yaml

substitutions:
  host: switch_kitchen
  area: Kitchen
  ipv4: 10.0.0.55

  link_1: 10.0.0.10/light/bedroom_light
  link_2: 10.0.0.10/switch/foo
  link_3: 10.0.0.11/light/balcony_light

i2c:
  sda: 3
  scl: 1
  scan: yes

sensor:
- <<: !include sensors/dht12.yaml
