<<: !include templates/switch.yaml

substitutions:
  host: switch_entrance
  area: Entrance
  ipv4: 10.0.0.56

  link_1: 10.0.0.11/light/balcony_light
  link_2: 10.0.0.11/light/balcony_light
  link_3: 10.0.0.11/light/balcony_light