
<<: !include share/common.yaml

substitutions:
  name: curtain_1
  area: Bedroom

wifi:
#  use_address: 10.0.0.188
  <<: !include share/wifi.yaml

esphome:
  <<: !include share/esp_modwifi.yaml
  includes:
    - components/curtain.h
  
globals:
  - id: cover_open
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: cover_reversed
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: cover_position
    type: float
    restore_value: yes
    initial_value: "0.5"

uart:
  - id: com_1
    tx_pin: GPIO01
    rx_pin: GPIO03
    baud_rate: 9600

logger:
  hardware_uart: UART1

custom_component:
  - lambda: |-
      return { new CustomAPI() };

cover:
  - platform: custom
    lambda: |-
      auto curtain = new CustomCover();
      App.register_component(curtain);
      return {curtain};
    covers:
      - id: cover_1
        name: $name Curtain
        device_class: blind
