ota:
api:
wifi:
  ssid: nest
  password: khongbiet
  fast_connect: true
  reboot_timeout: 0s
logger:
esphome:
  name: espnow
  platform: esp8266
  board: d1_mini_pro
  arduino_version: LATEST
  build_path: build/espnow
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 80000000L
    board_build.f_flash: 40000000L
  includes:
  - components/now.h

binary_sensor:
- platform: gpio
  pin: 2
  id: my_motion
  on_press:
  - lambda: ESPNow.send("my_motion on");
  on_release:
  - lambda: ESPNow.send("my_motion off");

custom_component:
- lambda: |-
    ESPNow.begin(2);
    return {};
