<<: !include .dimmer.yaml

substitutions:
  name: switch_5
  area: Switch 5
  code: '00000101'
  
  button_pin_1: "14"
  button_pin_2: "05"
  button_pin_3: "12"

  output_pin_1: "04"
  output_pin_2: "15"
  output_pin_3: "13"