<<: !include .switch.yaml

substitutions:
  <<: !include .pinout_tuya_switch.yaml
  host: switch_5
  name: Switch 5
  ipv4: 10.0.0.55

  link_1: 10.0.0.10/light/bedroom_light
  link_2: 10.0.0.55/switch/switch_2
  link_3: 10.0.0.11/light/balcony_light
