<<: !include common.yaml

esphome:
  name: $host
  board: modwifi
  platform: ESP8266
  build_path: build/$host
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600
  includes:
  - ../components/curtain.h

uart:
  id: uart0
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

cover:
  platform: custom
  lambda: |-
    auto component = new CustomCurtain();
    App.register_component(component);
    return {component};
  covers:
  - name: $area Curtain
    device_class: curtain