<<: !include sonoff.yaml

sensor:
#- <<: !include sensors/rssi.yaml
#- <<: !include sensors/uptime.yaml

power_supply:
  - id: psu_1
    enable_time: 20ms
    keep_on_time: 5s
    pin: 12 # relay pin

output:
  - platform: esp8266_pwm
    id: output_1
    pin: 1
    frequency: 100hz
    power_supply: psu_1
    
  - platform: esp8266_pwm
    id: output_2
    pin: 2
    frequency: 100hz
    power_supply: psu_1

  - platform: esp8266_pwm
    id: output_3
    pin: 3
    frequency: 100hz
    power_supply: psu_1

light:
  - platform: rgb
    name: $area Light
    blue: output_1
    green: output_2
    red: output_3