ota:
  password: !secret wifi_password

wifi:
  domain: ''
  use_address: $ipv4
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: $ipv4
    gateway: 0.0.0.0
    subnet: 255.255.255.0
  
esphome:
  name: $host
  board: esp8285
  platform: ESP8266
  build_path: build/${host}_minimal
  arduino_version: 2.4.2
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L
    board_build.ldscript: eagle.flash.1m.ld
