<<: !include sonoff.yaml

sensor:
#- <<: !include sensors/rssi.yaml
#- <<: !include sensors/uptime.yaml

output:
  - platform: gpio
    pin: 12
    id: output_1

light:
  - platform: binary
    output: output_1
    name: $area Light
