<<: !include common.yaml
  
esphome:
  name: $host
  board: esp8285
  platform: ESP8266
  build_path: build/$host
  arduino_version: LATEST
  esp8266_restore_from_flash: true
  includes:
  - components/esp-now/esp_now_connect.h
  platformio_options:
    upload_speed: 921600
    # board_build.f_cpu: 160000000L
    # board_build.f_flash: 80000000L
    board_build.ldscript: eagle.flash.1m.ld

status_led:
  pin:
    number: 13
    inverted: true
