<<: !include common.yaml

esphome:
  name: $host
  board: modwifi
  platform: ESP8266
  build_path: build/$host
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L

status_led:
  pin:
    number: 16
    inverted: true

script:
- id: on_single_tap_button_1
  then: []
- id: on_double_tap_button_1
  then: []
- id: on_long_press_button_1
  then: []

- id: on_single_tap_button_2
  then: []
- id: on_double_tap_button_2
  then: []
- id: on_long_press_button_2
  then: []

- id: on_single_tap_button_3
  then: []
- id: on_double_tap_button_3
  then: []
- id: on_long_press_button_3
  then: []

- id: on_swipe_up
  then: []
- id: on_swipe_down
  then: []
