<<: !include common.yaml

esphome:
  name: $host
  board: modwifi
  platform: ESP8266
  build_path: build/$host
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 921600
    board_build.f_cpu: 160000000L

http_request:
  useragent: esphome/$host
  timeout: 1s

status_led:
  pin:
    number: 16
    inverted: true

api:
  reboot_timeout: 0s
  services:
  - service: sync_button_state
    variables:
      button: int
      state: bool
    then:
    - lambda: >-
        switch (button) {
          case 1: id(output_1).publish_state(state); break;
          case 2: id(output_2).publish_state(state); break;
          case 3: id(output_3).publish_state(state); break;
        }

sensor:
#- <<: !include sensors/rssi.yaml
#- <<: !include sensors/uptime.yaml

switch:
- platform: gpio
  id: output_1
  icon: mdi:circle-double
  name: $area Switch 1
  pin: GPIO04
  
- platform: gpio
  id: output_2
  icon: mdi:circle-double
  name: $area Switch 2
  pin: GPIO15
  
- platform: gpio
  id: output_3
  icon: mdi:circle-double
  name: $area Switch 3
  pin: GPIO13

script:
- id: sync_state_1
  then:
  - if:
      condition:
        switch.is_on: output_1
      then:
      - http_request.post:
          url: http://${link_1}/turn_on
      else:
      - http_request.post:
          url: http://${link_1}/turn_off

- id: sync_state_2
  then:
  - if:
      condition:
        switch.is_on: output_2
      then:
      - http_request.post:
          url: http://${link_2}/turn_on
      else:
      - http_request.post:
          url: http://${link_2}/turn_off
- id: sync_state_3
  then:
  - if:
      condition:
        switch.is_on: output_3
      then:
      - http_request.post:
          url: http://${link_3}/turn_on
      else:
      - http_request.post:
          url: http://${link_3}/turn_off

binary_sensor:
- platform: gpio
  id: input_1
  pin:
    number: GPIO14
    inverted: true
  on_press:
  - then:
    - switch.toggle: output_1
    - script.execute: sync_state_1
- platform: gpio
  id: input_2
  pin:
    number: GPIO05
    inverted: true
  on_press:
  - then:
    - switch.toggle: output_2
    - script.execute: sync_state_2
- platform: gpio
  id: input_3
  pin:
    number: GPIO12
    inverted: true
  on_press:
  - then:
    - switch.toggle: output_3
    - script.execute: sync_state_3

