#use_address: ${host}.local
use_address: $ipv4
ssid: !secret wifi_ssid
password: !secret wifi_password
fast_connect: true
reboot_timeout: 0s
manual_ip:
  static_ip: $ipv4
  gateway: 10.0.0.1
  subnet: 255.255.255.0
ap:
  ssid: esphome__$host
  password: !secret wifi_password
  ap_timeout: 10s
  manual_ip:
    static_ip: 10.0.1.1
    gateway: 10.0.1.1
    subnet: 255.255.0.0
