#- name: Living Room
#  platform: ffmpeg
#  input: -rtsp_transport tcp -i rtsp://phong:123qwe@10.0.0.70:8554/unicast
#
#- name: Kitchen
#  platform: ffmpeg
#  input: -rtsp_transport tcp -i rtsp://phong:123qwe@10.0.0.71:8554/unicast

- platform: generic
  name: Kitchen
  username: root
  password: 123qwe
  authentication: basic
  still_image_url: https://10.0.0.71/cgi-bin/currentpic.cgi
  verify_ssl: false
  scan_interval: 1

- platform: generic
  name: Living Room
  username: root
  password: 123qwe
  authentication: basic
  still_image_url: https://10.0.0.70/cgi-bin/currentpic.cgi
  verify_ssl: false
  scan_interval: 1